openapi: "3.0"
info:
  title: Endpoints
  description: Методы справочника API сгруппированы по ресурсам. Чтобы выполнить операцию
    над ресурсом, отправьте HTTP-запрос к соответствующему URL или выполните RPC-вызов.
    Подробнее об архитектуре API Яндекс.Облака, см. [Концепции API Яндекс.Облака](/docs/api-design-guide/).
  version: Version not set.
paths:
  /endpoints/{apiEndpointId}:
    get:
      tags:
      - ApiEndpoint
      operationId: ApiEndpointGet
      parameters:
      - name: apiEndpointId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiEndpoint'
      x-y-navtitle: get
  /endpoints:
    get:
      tags:
      - ApiEndpoint
      operationId: ApiEndpointList
      parameters:
      - name: pageSize
        in: query
        schema:
          type: string
          format: int64
      - name: pageToken
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListApiEndpointsResponse'
      x-y-navtitle: list
components:
  schemas:
    ApiEndpoint:
      type: object
      properties:
        id:
          type: string
        address:
          type: string
    ListApiEndpointsResponse:
      type: object
      properties:
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/ApiEndpoint'
        nextPageToken:
          type: string
tags:
- name: ApiEndpoint
