DOCS()

OWNER(g:kikimr)

PEERDIR (
    kikimr/tools/docs
)

SET(YDB_DOCS_ARCHIVE docs.tar.gz)
SET(YDB_DOCS_BUILD_ROOT ${ARCADIA_BUILD_ROOT}/kikimr/docs)

RUN_PROGRAM(
    kikimr/tools/docs
        --version 1
        --skip-single-page
        --config ${ARCADIA_ROOT}/kikimr/docs/index.yml
        --docs-dir ${ARCADIA_ROOT}/kikimr/docs
        --theme-dir ${ARCADIA_ROOT}/kikimr/tools/docs/material-theme
        --output-tar ${YDB_DOCS_ARCHIVE}
    CWD ${YDB_DOCS_BUILD_ROOT}
    OUT_NOAUTO ${YDB_DOCS_BUILD_ROOT}/${YDB_DOCS_ARCHIVE}
    IN
        api/api_libs_overview.md
        api/cli.md
        api/client_libs.md
        api/cpp_api.md
        api/error_handling.md
        api/information_schema.md
        api/java_api.md
        api/minikql.md
        api/minikql_ast.md
        api/minikql_text.md
        api/nicedb.md
        api/python_api.md
        api/query_execution_plan.md
        api/rest.md
        api/rpc.md
        api/yql_prepared_statements.md
        api/yql_transactions.md
        architecture/layer_distribution.md
        architecture/layer_replication.md
        architecture/layer_sql.md
        architecture/layer_storage.md
        architecture/layer_transaction.md
        architecture/overview.md
        architecture/overview.src.md
        best_practices/batch_upload.md
        best_practices/column_families.md
        best_practices/import_from_yt.md
        best_practices/paging.md
        best_practices/schema_design.md
        best_practices/secondary_indexes.md
        best_practices/ttl.md
        best_practices/yql_advices.md
        builtins/aggregation.md
        builtins/basic.md
        builtins/dict.md
        builtins/list.md
        builtins/types.md
        builtins/window.md
        changelog/18_6/18_6_14.md
        changelog/18_6/18_6_15.md
        changelog/18_6/18_6_16.md
        changelog/index.md
        concepts/comparision.md
        concepts/databases.md
        concepts/datamodel.md
        concepts/datatypes.md
        concepts/ha.md
        concepts/iam.md
        concepts/olap.md
        concepts/queries.md
        concepts/secondary_indexes.md
        concepts/sessions.md
        concepts/strict_consistency.md
        concepts/transactions.md
        css/extra.css
        differences_from/clickhouse.md
        differences_from/hive.md
        differences_from/mssql.md
        differences_from/mysql.md
        differences_from/oracle.md
        differences_from/postgresql.md
        downloads.md
        faq/cli.md
        faq/errors.md
        faq/faq_product.md
        faq/faq_sql.md
        faq/performance.md
        faq/queries.md
        faq.md
        getting_started/confdeploy.md
        getting_started/create_manage_database.md
        getting_started/crud.md
        getting_started/get_cluster.md
        getting_started/index.md
        getting_started/public_cluster.md
        getting_started/setup_network_access.md
        getting_started/start_auth.md
        getting_started/start_cpp.md
        getting_started/start_java.md
        getting_started/start_local_cluster.md
        getting_started/start_python.md
        getting_started/start_rest.md
        guides/beginners.md
        guides/jupyter.md
        guides/metaprogramming.md
        guides/schedule.md
        guides/udaf.md
        howto/apply_iam.md
        howto/index.md
        howto/monitoring_solomon.md
        _assets/best_practices_yt_import_dbname.png
        _assets/coordinator.png
        _assets/cpp_classes.png
        _assets/datamodel_rtable.png
        _assets/datamodel_ydb_tree.png
        _assets/datashard_scheme.png
        _assets/db_ui_create_database_button.png
        _assets/db_ui_create_home_database.png
        _assets/db_ui_create_new_database.png
        _assets/db_ui_drop_database_button.png
        _assets/db_ui_edit_database_button.png
        _assets/db_ui_entrance_home_database.png
        _assets/db_ui_give_me_token.png
        _assets/db_ui_info_cluster_api.png
        _assets/db_ui_list_databases.png
        _assets/db_ui_open_yql_kit.png
        _assets/db_ui_run_create_table.png
        _assets/db_ui_run_delete.png
        _assets/db_ui_run_select.png
        _assets/db_ui_run_update.png
        _assets/db_ui_table_details_kit.png
        _assets/db_ui_table_preview.png
        _assets/db_ui_yql_kit_panel.png
        _assets/garbage.png
        _assets/hive_data_scheme.png
        _assets/hive_external_interface.png
        _assets/hive_local_a.png
        _assets/hive_local_b.png
        _assets/kikimrstructure1.png
        _assets/kikimrstructure2.png
        _assets/kikimrstructure3.png
        _assets/kikimrstructure4.png
        _assets/kikimrstructure5.png
        _assets/kikimrstructure6.png
        _assets/kikimrstructure7.png
        _assets/kikimrstructure8.png
        _assets/logoblobid.png
        _assets/multitenancy.png
        _assets/nodewarden.png
        _assets/pdiskchunk.png
        _assets/puncher_request_4slb_form.png
        _assets/puncher_request_4slb_form_ydb_ru.png
        _assets/puncher_request_4slb_form_ydb_ru_prestable.png
        _assets/puncher_request_form.png
        _assets/puncher_request_form_ydb_ru.png
        _assets/puncher_request_form_ydb_ru_prestable.png
        _assets/scheduler.png
        _assets/tablet-log2.png
        _assets/ydb_example_create_table.png
        _assets/ydb_example_create_table_full.png
        _assets/ydb_example_select_table.png
        index.md
        index.yml
        interfaces/cli.md
        interfaces/http.md
        interfaces/jdbc.md
        interfaces/python.md
        interfaces/web.md
        internals/actors.md
        internals/configuration.md
        internals/crossdc.md
        internals/datashard_autosplit.md
        internals/domains.md
        internals/dynamicconfiguration.md
        internals/erasure.md
        internals/errors_in_api_requests.md
        internals/external_proxies.md
        internals/glossary.md
        internals/interconnect.md
        internals/localdatabase.md
        internals/multitenancy.md
        internals/nalf.md
        internals/pdisk.md
        internals/resource_broker.md
        internals/slicedeploy.md
        internals/subdomains.md
        internals/tablet_blobstorage_controller.md
        internals/tablet_blobstorage_overview.md
        internals/tablet_blobstorage_proxy.md
        internals/tablet_coordinator.md
        internals/tablet_datashard.md
        internals/tablet_datashard_cc.md
        internals/tablet_datashard_ooo.md
        internals/tablet_datashard_smallbank.md
        internals/tablet_datashard_soft_updates.md
        internals/tablet_dsproxy.md
        internals/tablet_election.md
        internals/tablet_hive.md
        internals/tablet_hive_balancer.md
        internals/tablet_key_value.md
        internals/tablet_mediator.md
        internals/tablet_pipes.md
        internals/tablet_pq.md
        internals/tablet_schemeshard.md
        internals/tablet_slaves.md
        internals/tablet_state_storage.md
        internals/tablet_txproxy.md
        internals/tablets.md
        internals/tx_deterministic.md
        internals/tx_processing.md
        internals/tx_processing_graph.md
        internals/vdisk.md
        internals/vdisk_replication.md
        libraries/client.md
        libraries/embedded.md
        libraries/purecalc.md
        libraries/testing.md
        maintenance/backup.md
        maintenance/diag_report.md
        maintenance/dump_schema.md
        maintenance/import.md
        maintenance/restore.md
        maintenance/version_details.md
        misc/schema.md
        misc/syntax_highlight.md
        misc/type_string.md
        overview.md
        porting/porting.md
        quickstart.md
        release_notes.md
        security/basics.md
        security/data_encryption.md
        troubleshooting/collect_db_debug_info.md
        troubleshooting/common_errors.md
        troubleshooting/overview.md
        troubleshooting/query_behavior.md
        troubleshooting/understand_debug_logs.md
        whitepapers.md
)

END()
