openapi: 3.0.0
info:
  title: Load Testing API
  description: This API reference is organized by resource. Actions are performed
    by sending HTTP requests to resource URLs or making RPC calls. For more information
    about API architecture, see [API Concepts](/docs/api-design-guide/).
  version: v1
  x-y-docUri: api-ref
  x-y-baseUrl: https://loadtesting.api.cloud.yandex.net
paths: {}
components:
  schemas:
    CreateStorageMetadata:
      type: object
      properties:
        storageId:
          type: string
    DeleteStorageMetadata:
      type: object
      properties:
        storageId:
          type: string
    Empty:
      description: Empty JSON object `` {} ``.
      type: object
      maxProperties: 0
    ListResourcePresetsResponse:
      type: object
      properties:
        resourcePresets:
          type: array
          items:
            $ref: '#/components/schemas/ResourcePreset'
        nextPageToken:
          type: string
    ListStorageResponse:
      type: object
      properties:
        storages:
          type: array
          items:
            $ref: '#/components/schemas/Storage'
        nextPageToken:
          type: string
    Operation:
      description: An Operation resource. For more information, see [Operation](/docs/api-design-guide/concepts/operation).
      type: object
      allOf:
      - type: object
        properties:
          id:
            description: ID of the operation.
            type: string
          description:
            description: Description of the operation. 0-256 characters long.
            type: string
          createdAt:
            description: |-
              Creation timestamp.

              String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
            type: string
            format: date-time
          createdBy:
            description: ID of the user or service account who initiated the operation.
            type: string
          modifiedAt:
            description: |-
              The time when the Operation resource was last modified.

              String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
            type: string
            format: date-time
          done:
            description: |-
              If the value is `false`, it means the operation is still in progress.
              If `true`, the operation is completed, and either `error` or `response` is available.
            type: boolean
            format: boolean
          metadata:
            description: |-
              Service-specific metadata associated with the operation.
              It typically contains the ID of the target resource that the operation is performed on.
              Any method that returns a long-running operation should document the metadata type, if any.
            type: object
      - title: result
        type: object
        maxProperties: 1
        properties:
          error:
            $ref: '#/components/schemas/Status'
            description: The error result of the operation in case of failure or cancellation.
          response:
            description: |-
              The normal response of the operation in case of success.
              If the original method returns no data on success, such as Delete,
              the response is [google.protobuf.Empty](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#empty).
              If the original method is the standard Create/Update,
              the response should be the target resource of the operation.
              Any method that returns a long-running operation should document the response type, if any.
            type: object
    ResourcePreset:
      description: A ResourcePreset resource for describing VM configuration presets
        for TankInstance.
      type: object
      properties:
        presetId:
          description: ID of the ResourcePreset resource.
          type: string
        name:
          description: Name of the ResourcePreset resource.
          type: string
        description:
          description: Description of the ResourcePreset resource.
          type: string
        cores:
          description: Number of CPU cores for a Tank created with the preset.
          type: string
          format: int64
        memory:
          description: RAM volume for a Tank created with the preset, in bytes.
          type: string
          format: int64
        diskSize:
          description: Disk size for a tank created with the preset, in bytes.
          type: string
          format: int64
    Status:
      description: The error result of the operation in case of failure or cancellation.
      type: object
      properties:
        code:
          description: Error code. An enum value of [google.rpc.Code](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto).
          type: integer
          format: int32
        message:
          description: An error message.
          type: string
        details:
          description: A list of messages that carry the error details.
          type: array
          items:
            type: object
    Storage:
      type: object
      properties:
        id:
          type: string
        folderId:
          type: string
        name:
          type: string
        description:
          type: string
        labels:
          type: object
          additionalProperties:
            type: string
        createdAt:
          description: String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text
            format.
          type: string
          format: date-time
        objectStorageBucket:
          type: string
        usedSize:
          type: string
          format: int64
    StorageObject:
      type: object
      properties:
        objectStorageBucket:
          type: string
        objectStorageFilename:
          type: string
tags:
- name: ResourcePreset
- name: Storage
