openapi: 3.0.0
info:
  title: Load Testing API
  description: This API reference is organized by resource. Actions are performed
    by sending HTTP requests to resource URLs or making RPC calls. For more information
    about API architecture, see [API Concepts](/docs/api-design-guide/).
  version: v2
  x-y-docUri: api-ref
  x-y-baseUrl: https://loadtesting.api.cloud.yandex.net
paths: {}
components:
  schemas:
    AgentInstance:
      type: object
      properties:
        id:
          type: string
        folderId:
          type: string
        createdAt:
          description: String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text
            format.
          type: string
          format: date-time
        computeInstanceUpdatedAt:
          description: String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text
            format.
          type: string
          format: date-time
        name:
          type: string
        description:
          type: string
        labels:
          type: object
          additionalProperties:
            type: string
        serviceAccountId:
          type: string
        presetId:
          type: string
        yandexTankVersion:
          type: string
        status:
          $ref: '#/components/schemas/AgentInstanceStatus_in_AgentInstance_status'
        errors:
          type: array
          items:
            type: string
        currentJob:
          type: string
        computeInstanceId:
          description: Compute Instance Id and status
          type: string
        agentVersion:
          $ref: '#/components/schemas/AgentVersion_in_AgentInstance_agentVersion'
    AgentInstanceStatus:
      type: string
      enum:
      - PREPARING_TEST
      - READY_FOR_TEST
      - TESTING
      - TANK_FAILED
      - PROVISIONING
      - STOPPING
      - STOPPED
      - STARTING
      - RESTARTING
      - UPDATING
      - ERROR
      - CRASHED
      - DELETING
      - LOST_CONNECTION_WITH_TANK
      - INITIALIZING_CONNECTION
    AgentVersion:
      type: object
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/AgentVersionVersionStatus_in_AgentVersion_status'
        revision:
          type: string
          format: int64
        description:
          type: string
        statusComment:
          type: string
    AgentVersionVersionStatus:
      type: string
      enum:
      - ACTUAL
      - DEPRECATED
      - OUTDATED
      - UNSET
      - UNKNOWN
      - TESTING
    Autostop:
      type: object
      properties:
        autostopType:
          $ref: '#/components/schemas/AutostopAutostopType_in_Autostop_autostopType'
        autostopCriteria:
          type: string
        autostopCase:
          type: string
    AutostopAutostopType:
      type: string
      enum:
      - TIME
      - HTTP
      - NET
      - QUANTILE
      - INSTANCES
      - METRIC_LOWER
      - METRIC_HIGHER
      - STEADY_CUMULATIVE
      - LIMIT
      - TOTAL_TIME
      - TOTAL_HTTP
      - TOTAL_NET
      - NEGATIVE_HTTP
      - NEGATIVE_NET
      - HTTP_TREND
    CreateAgentInstanceMetadata:
      type: object
      properties:
        agentInstanceId:
          type: string
    CreateTestMetadata:
      type: object
      properties:
        testId:
          type: string
    DeleteAgentInstanceMetadata:
      type: object
      properties:
        agentInstanceId:
          type: string
    DeleteTestMetadata:
      type: object
      properties:
        testId:
          type: string
    DnsRecordSpec:
      type: object
      properties:
        fqdn:
          description: |-
            Required.
            FQDN (required)
          type: string
        dnsZoneId:
          description: DNS zone id (optional, if not set, private zone used)
          type: string
        ttl:
          description: |-
            DNS record ttl, values in 0-86400 (optional)

            Acceptable values are 0 to 86400, inclusive.
          type: string
          format: int64
        ptr:
          description: When set to true, also create PTR DNS record (optional)
          type: boolean
          format: boolean
    Empty:
      description: Empty JSON object `` {} ``.
      type: object
      maxProperties: 0
    FieldMask:
      description: |-
        A comma-separated names off ALL fields to be updated.
        Ðžnly the specified fields will be changed. The others will be left untouched.
        If the field is specified in `` updateMask `` and no value for that field was sent in the request,
        the field's value will be reset to the default. The default value for most fields is null or 0.

        If `` updateMask `` is not sent in the request, all fields' values will be updated.
        Fields specified in the request will be updated to provided values.
        The rest of the fields will be reset to the default.
      type: string
    GetAgentInstanceResponse:
      type: object
      properties:
        agentInstance:
          $ref: '#/components/schemas/AgentInstance_in_GetAgentInstanceResponse_agentInstance'
    IpVersion:
      description: |2-
         - IPV4: IPv4 address, for example 192.0.2.235.
         - IPV6: IPv6 address. Not available yet.
      type: string
      enum:
      - IPV4
      - IPV6
    ListAgentInstancesResponse:
      type: object
      properties:
        folderId:
          type: string
        agentInstances:
          type: array
          items:
            $ref: '#/components/schemas/AgentInstance'
        nextPageToken:
          type: string
    ListTestsResponse:
      type: object
      properties:
        folderId:
          type: string
        tests:
          type: array
          items:
            $ref: '#/components/schemas/Test'
        nextPageToken:
          type: string
    NetworkInterfaceSpec:
      type: object
      properties:
        subnetId:
          description: |-
            Required.
            ID of the subnet.

            The maximum string length in characters is 50.
          type: string
        primaryV4AddressSpec:
          $ref: '#/components/schemas/PrimaryAddressSpec_in_NetworkInterfaceSpec_primaryV4AddressSpec'
        primaryV6AddressSpec:
          $ref: '#/components/schemas/PrimaryAddressSpec_in_NetworkInterfaceSpec_primaryV6AddressSpec'
        securityGroupIds:
          description: ID's of security groups attached to the interface
          type: array
          items:
            type: string
    OneToOneNatSpec:
      type: object
      properties:
        ipVersion:
          $ref: '#/components/schemas/IpVersion_in_OneToOneNatSpec_ipVersion'
        address:
          type: string
        dnsRecordSpecs:
          description: External DNS configuration
          type: array
          items:
            $ref: '#/components/schemas/DnsRecordSpec'
    Operation:
      description: An Operation resource. For more information, see [Operation](/docs/api-design-guide/concepts/operation).
      type: object
      allOf:
      - type: object
        properties:
          id:
            description: ID of the operation.
            type: string
          description:
            description: Description of the operation. 0-256 characters long.
            type: string
          createdAt:
            description: |-
              Creation timestamp.

              String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
            type: string
            format: date-time
          createdBy:
            description: ID of the user or service account who initiated the operation.
            type: string
          modifiedAt:
            description: |-
              The time when the Operation resource was last modified.

              String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
            type: string
            format: date-time
          done:
            description: |-
              If the value is `false`, it means the operation is still in progress.
              If `true`, the operation is completed, and either `error` or `response` is available.
            type: boolean
            format: boolean
          metadata:
            description: |-
              Service-specific metadata associated with the operation.
              It typically contains the ID of the target resource that the operation is performed on.
              Any method that returns a long-running operation should document the metadata type, if any.
            type: object
      - title: result
        type: object
        maxProperties: 1
        properties:
          error:
            $ref: '#/components/schemas/rpcStatus'
            description: The error result of the operation in case of failure or cancellation.
          response:
            description: |-
              The normal response of the operation in case of success.
              If the original method returns no data on success, such as Delete,
              the response is [google.protobuf.Empty](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#empty).
              If the original method is the standard Create/Update,
              the response should be the target resource of the operation.
              Any method that returns a long-running operation should document the response type, if any.
            type: object
    PrimaryAddressSpec:
      type: object
      properties:
        address:
          description: |-
            An IPv4 internal network address that is assigned to the instance for this network interface.
            If not specified by the user, an unused internal IP is assigned by the system.
          type: string
        oneToOneNatSpec:
          $ref: '#/components/schemas/OneToOneNatSpec_in_PrimaryAddressSpec_oneToOneNatSpec'
        dnsRecordSpecs:
          description: Internal DNS configuration
          type: array
          items:
            $ref: '#/components/schemas/DnsRecordSpec'
    RestartAgentInstanceMetadata:
      type: object
      properties:
        agentInstanceId:
          type: string
    StartAgentInstanceMetadata:
      type: object
      properties:
        agentInstanceId:
          type: string
    StopAgentInstanceMetadata:
      type: object
      properties:
        agentInstanceId:
          type: string
    StopTestMetadata:
      type: object
      properties:
        testId:
          type: string
    StorageObject:
      type: object
      properties:
        objectStorageBucket:
          type: string
        objectStorageFilename:
          type: string
    Test:
      type: object
      allOf:
      - type: object
        properties:
          id:
            type: string
          folderId:
            type: string
          name:
            type: string
          description:
            type: string
          labels:
            type: object
            additionalProperties:
              type: string
          createdAt:
            description: String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt)
              text format.
            type: string
            format: date-time
          startedAt:
            description: String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt)
              text format.
            type: string
            format: date-time
          finishedAt:
            description: String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt)
              text format.
            type: string
            format: date-time
          updatedAt:
            description: String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt)
              text format.
            type: string
            format: date-time
          generator:
            $ref: '#/components/schemas/TestGenerator'
          agentInstanceId:
            description: AgentInstance ID where Test is running.
            type: string
          targetAddress:
            description: Target VM ID.
            type: string
          targetPort:
            type: string
            format: int64
          targetVersion:
            description: Version of object under test.
            type: string
          config:
            description: Test details
            type: string
          cases:
            type: array
            items:
              type: string
          status:
            $ref: '#/components/schemas/TestStatus'
          errors:
            type: array
            items:
              type: string
          favorite:
            type: boolean
            format: boolean
          imbalancePoint:
            type: string
            format: int64
          imbalanceTs:
            type: string
            format: int64
          autostops:
            type: array
            items:
              $ref: '#/components/schemas/Autostop'
      - title: payload
        type: object
        maxProperties: 1
        properties:
          payloadUrls:
            type: string
          payloadId:
            type: string
    TestGenerator:
      type: string
      enum:
      - PANDORA
      - PHANTOM
    TestStatus:
      type: string
      enum:
      - CREATED
      - INITIATED
      - PREPARING
      - RUNNING
      - FINISHING
      - DONE
      - POST_PROCESSING
      - FAILED
      - STOPPING
      - STOPPED
      - AUTOSTOPPED
    UpdateTestMetadata:
      type: object
      properties:
        testId:
          type: string
    UpgradeImageAgentInstanceMetadata:
      type: object
      properties:
        agentInstanceId:
          type: string
    ValidateConfigResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ValidateConfigResponseStatus_in_ValidateConfigResponse_status'
        errors:
          type: array
          items:
            type: string
    ValidateConfigResponseStatus:
      type: string
      enum:
      - OK
      - FAILED
    rpcStatus:
      description: The error result of the operation in case of failure or cancellation.
      type: object
      properties:
        code:
          description: Error code. An enum value of [google.rpc.Code](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto).
          type: integer
          format: int32
        message:
          description: An error message.
          type: string
        details:
          description: A list of messages that carry the error details.
          type: array
          items:
            type: object
    AgentInstanceStatus_in_AgentInstance_status:
      description: 'Current status: current job, errors, Status'
      type: string
      enum:
      - PREPARING_TEST
      - READY_FOR_TEST
      - TESTING
      - TANK_FAILED
      - PROVISIONING
      - STOPPING
      - STOPPED
      - STARTING
      - RESTARTING
      - UPDATING
      - ERROR
      - CRASHED
      - DELETING
      - LOST_CONNECTION_WITH_TANK
      - INITIALIZING_CONNECTION
    AgentVersion_in_AgentInstance_agentVersion:
      type: object
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/AgentVersionVersionStatus_in_AgentVersion_status'
        revision:
          type: string
          format: int64
        description:
          type: string
        statusComment:
          type: string
    AgentVersionVersionStatus_in_AgentVersion_status:
      type: string
      enum:
      - ACTUAL
      - DEPRECATED
      - OUTDATED
      - UNSET
      - UNKNOWN
      - TESTING
    AutostopAutostopType_in_Autostop_autostopType:
      type: string
      enum:
      - TIME
      - HTTP
      - NET
      - QUANTILE
      - INSTANCES
      - METRIC_LOWER
      - METRIC_HIGHER
      - STEADY_CUMULATIVE
      - LIMIT
      - TOTAL_TIME
      - TOTAL_HTTP
      - TOTAL_NET
      - NEGATIVE_HTTP
      - NEGATIVE_NET
      - HTTP_TREND
    AgentInstance_in_GetAgentInstanceResponse_agentInstance:
      type: object
      properties:
        id:
          type: string
        folderId:
          type: string
        createdAt:
          description: String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text
            format.
          type: string
          format: date-time
        computeInstanceUpdatedAt:
          description: String in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text
            format.
          type: string
          format: date-time
        name:
          type: string
        description:
          type: string
        labels:
          type: object
          additionalProperties:
            type: string
        serviceAccountId:
          type: string
        presetId:
          type: string
        yandexTankVersion:
          type: string
        status:
          $ref: '#/components/schemas/AgentInstanceStatus_in_AgentInstance_status'
        errors:
          type: array
          items:
            type: string
        currentJob:
          type: string
        computeInstanceId:
          description: Compute Instance Id and status
          type: string
        agentVersion:
          $ref: '#/components/schemas/AgentVersion_in_AgentInstance_agentVersion'
    PrimaryAddressSpec_in_NetworkInterfaceSpec_primaryV4AddressSpec:
      description: Primary IPv4 address that will be assigned to the instance for
        this network interface.
      type: object
      properties:
        address:
          description: |-
            An IPv4 internal network address that is assigned to the instance for this network interface.
            If not specified by the user, an unused internal IP is assigned by the system.
          type: string
        oneToOneNatSpec:
          $ref: '#/components/schemas/OneToOneNatSpec_in_PrimaryAddressSpec_oneToOneNatSpec'
        dnsRecordSpecs:
          description: Internal DNS configuration
          type: array
          items:
            $ref: '#/components/schemas/DnsRecordSpec'
    PrimaryAddressSpec_in_NetworkInterfaceSpec_primaryV6AddressSpec:
      description: Primary IPv6 address that will be assigned to the instance for
        this network interface. IPv6 not available yet.
      type: object
      properties:
        address:
          description: |-
            An IPv4 internal network address that is assigned to the instance for this network interface.
            If not specified by the user, an unused internal IP is assigned by the system.
          type: string
        oneToOneNatSpec:
          $ref: '#/components/schemas/OneToOneNatSpec_in_PrimaryAddressSpec_oneToOneNatSpec'
        dnsRecordSpecs:
          description: Internal DNS configuration
          type: array
          items:
            $ref: '#/components/schemas/DnsRecordSpec'
    IpVersion_in_OneToOneNatSpec_ipVersion:
      description: |-
        External IP address version.

         - IPV4: IPv4 address, for example 192.0.2.235.
         - IPV6: IPv6 address. Not available yet.
      type: string
      enum:
      - IPV4
      - IPV6
    OneToOneNatSpec_in_PrimaryAddressSpec_oneToOneNatSpec:
      description: |-
        An external IP address configuration.
        If not specified, then this instance will have no external internet access.
      type: object
      properties:
        ipVersion:
          $ref: '#/components/schemas/IpVersion_in_OneToOneNatSpec_ipVersion'
        address:
          type: string
        dnsRecordSpecs:
          description: External DNS configuration
          type: array
          items:
            $ref: '#/components/schemas/DnsRecordSpec'
    ValidateConfigResponseStatus_in_ValidateConfigResponse_status:
      type: string
      enum:
      - OK
      - FAILED
tags:
- name: AgentInstance
- name: Test
