openapi: '3.0'
info:
  title: Yandex Monitoring API
  description: >-
    Методы справочника API сгруппированы по ресурсам. Чтобы выполнить операцию
    над ресурсом, отправьте HTTP-запрос к соответствующему URL или выполните
    RPC-вызов. Подробнее об архитектуре API Яндекс.Облака, см. [Концепции API
    Яндекс.Облака](/docs/api-design-guide/).
  version: Version not set.
  x-y-docUri: api-ref
  x-y-baseUrl: https://monitoring.api.cloud.yandex.net
paths:
  /monitoring/v1/data/read:
    post:
      tags:
        - MetricsData
      summary: Возвращает данные метрик.
      operationId: MetricsDataRead
      parameters:
        - name: cloudId
          in: query
          description: |-
            Обязательное поле.
            Идентификатор облака, которому принадлежит метрика.

            Максимальная длина строки в символах — 50.
          schema:
            type: string
        - name: folderId
          in: query
          description: |-
            Обязательное поле.
            Идентификатор каталога, которому принадлежит метрика.

            Максимальная длина строки в символах — 50.
          schema:
            type: string
      requestBody:
        description: |-
          Обязательное поле.
          Параметры запроса.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataQuery'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadDataResult'
      x-y-navtitle: read
  /monitoring/v1/data/write:
    post:
      tags:
        - MetricsData
      summary: Записывает данные метрик.
      operationId: MetricsDataWrite
      parameters:
        - name: cloudId
          in: query
          description: |-
            Обязательное поле.
            Идентификатор облака, которому принадлежит метрика.

            Максимальная длина строки в символах — 50.
          schema:
            type: string
        - name: folderId
          in: query
          description: |-
            Обязательное поле.
            Идентификатор каталога, которому принадлежит метрика.

            Максимальная длина строки в символах — 50.
          schema:
            type: string
        - name: service
          in: query
          description: >-
            Обязательное поле.

            Идентификатор сервиса, которому принадлежит метрика. Для
            пользовательских метрик `service=custom`.
          schema:
            type: string
      requestBody:
        description: |-
          Обязательное поле.
          Содержимое запроса.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JsonFormat'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WriteDataResponse'
      x-y-navtitle: write
  /monitoring/v1/metrics:
    get:
      tags:
        - MetricsMeta
      summary: Возвращает список метрик.
      operationId: MetricsMetaListMetrics
      parameters:
        - name: cloudId
          in: query
          description: |-
            Обязательное поле.
            Идентификатор облака, которому принадлежит метрика.

            Максимальная длина строки в символах — 50.
          schema:
            type: string
        - name: folderId
          in: query
          description: |-
            Обязательное поле.
            Идентификатор каталога, которому принадлежит метрика.

            Максимальная длина строки в символах — 50.
          schema:
            type: string
        - name: page
          in: query
          description: Номер страницы.
          schema:
            type: string
            format: int64
        - name: pageSize
          in: query
          description: Количество метрик в одной странице ответа.
          schema:
            type: string
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListMetricsResponse'
      x-y-navtitle: listMetrics
components:
  schemas:
    DataQuery:
      type: object
      properties:
        program:
          description: |-
            Обязательное поле.
            Текст запроса.
          type: string
        fromTime:
          description: >-
            Обязательное поле.

            Начальная точка интервала. Строка в формате
            [ISO8601](https://ru.wikipedia.org/wiki/ISO_8601).
          type: string
          format: int64
        toTime:
          description: >-
            Обязательное поле.

            Конечная точка интервала. Строка в формате
            [ISO8601](https://ru.wikipedia.org/wiki/ISO_8601).
          type: string
          format: int64
        downsampling:
          $ref: '#/components/schemas/DataQueryDownsampling_in_DataQuery_downsampling'
    DataQueryDownsampling:
      type: object
      properties:
        maxPoints:
          description: >-
            Максимальное количество точек, которое будет получено в ответе на
            запрос.


            Допустимые значения — от 10 до 10000 включительно.
          type: string
          format: int64
        gridMillis:
          description: >-
            Ширина временного окна (сетка) в миллисекундах. Используется для
            прореживания.

            Точки внутри окна объединяются в одну при помощи функции агрегации.


            Значение должно быть больше 0.
          type: string
          format: int64
        aggregation:
          $ref: >-
            #/components/schemas/GridAggregation_in_DataQueryDownsampling_aggregation
        fill:
          $ref: '#/components/schemas/FillGap_in_DataQueryDownsampling_fill'
    FillGap:
      description: |2-
         - NULL: Возвращает `null` в качестве значения метрики и `timestamp` в качестве временной метки. Значение по умолчанию.
         - NONE: Не возвращает значений.
         - PREVIOUS: Возвращает значение из предыдущей временной точки.
      type: string
      enum:
        - 'NULL'
        - NONE
        - PREVIOUS
    GridAggregation:
      description: |-
        Список доступных агрегирующий функций, используемых при прореживании.

         - MAX: Максимум.
         - MIN: Минимум.
         - SUM: Сумма.
         - AVG: Среднее значение. Значение по умолчанию.
         - LAST: Последнее значение.
         - COUNT: Количество точек.
      type: string
      enum:
        - MAX
        - MIN
        - SUM
        - AVG
        - LAST
        - COUNT
    JsonFormat:
      type: object
      properties:
        ts:
          description: Общая временная метка для всех метрик.
          type: string
          format: int64
        labels:
          description: >-
            Список меток общих для всех передаваемых метрик в формате
            `ключ:значение`.
          type: object
          additionalProperties:
            type: string
        metrics:
          description: Список метрик.
          type: array
          items:
            $ref: '#/components/schemas/JsonFormatMetric'
    JsonFormatMetric:
      type: object
      properties:
        name:
          description: |-
            Обязательное поле.
            Имя метрики.
          type: string
        labels:
          description: Список меток метрики в формате `ключ:значение`.
          type: object
          additionalProperties:
            type: string
        kind:
          $ref: '#/components/schemas/MetricKind_in_JsonFormatMetric_kind'
        ts:
          description: >-
            Временная метка в формате `timestamp`. Если не указано, будет
            использовано текущее время.
          type: string
          format: int64
        value:
          description: |-
            Обязательное поле.
            Значение метрики в указанной точке.
          type: number
          format: double
        timeseries:
          description: Список из нескольких точек.
          type: array
          items:
            $ref: '#/components/schemas/JsonFormatPoint'
    JsonFormatPoint:
      type: object
      properties:
        ts:
          description: Временная точка в формате `timestamp`.
          type: string
          format: int64
        value:
          description: Значение метрики в указанной точке.
          type: number
          format: double
    ListMetricsResponse:
      type: object
      properties:
        result:
          description: Список метрик.
          type: array
          items:
            $ref: '#/components/schemas/MetricMeta'
        page:
          $ref: '#/components/schemas/PageOptions_in_ListMetricsResponse_page'
    MetricKind:
      description: |2-
         - DGAUGE: Числовой показатель. Задается дробным числом.
         - IGAUGE: Числовой показатель. Задается целым числом.
         - COUNTER: Счетчик.
         - RATE: Производная.
      type: string
      enum:
        - DGAUGE
        - IGAUGE
        - COUNTER
        - RATE
    MetricMeta:
      type: object
      properties:
        name:
          description: Имя метрики.
          type: string
        labels:
          description: Список меток метрики в формате `ключ:значение`.
          type: object
          additionalProperties:
            type: string
        kind:
          $ref: '#/components/schemas/MetricKind_in_MetricMeta_kind'
        createdAt:
          description: >-
            Время создания (записи первой точки) метрики. Строка в формате
            [ISO8601](https://ru.wikipedia.org/wiki/ISO_8601).
          type: string
          format: int64
    PageOptions:
      type: object
      properties:
        pagesCount:
          description: Количество страниц в ответе.
          type: string
          format: int64
        totalCount:
          description: Общее количество метрик в ответе.
          type: string
          format: int64
        pageSize:
          description: Количество метрик на одной странице ответа.
          type: string
          format: int64
        current:
          description: Номер запрошенной страницы.
          type: string
          format: int64
    ReadDataResult:
      type: object
      properties:
        vector:
          description: Список метрик.
          type: array
          items:
            $ref: '#/components/schemas/Timeseries'
    Timeseries:
      type: object
      properties:
        kind:
          $ref: '#/components/schemas/MetricKind_in_Timeseries_kind'
        name:
          description: Имя метрики.
          type: string
        labels:
          description: Список меток метрики в формате `ключ:значение`.
          type: object
          additionalProperties:
            type: string
        timestamps:
          description: Список временных точек метрики в формате `timestamp`.
          type: array
          items:
            type: string
            format: int64
        values:
          description: Список значений метрики.
          type: array
          items:
            type: number
            format: double
    WriteDataResponse:
      type: object
      properties:
        metricsPushed:
          description: Количество успешно записанных метрик.
          type: string
          format: int64
        errors:
          description: Сообщение об ошибке, если запись завершилась неуспешно.
          type: string
    DataQueryDownsampling_in_DataQuery_downsampling:
      description: Параметры прореживания.
      type: object
      properties:
        maxPoints:
          description: >-
            Максимальное количество точек, которое будет получено в ответе на
            запрос.


            Допустимые значения — от 10 до 10000 включительно.
          type: string
          format: int64
        gridMillis:
          description: >-
            Ширина временного окна (сетка) в миллисекундах. Используется для
            прореживания.

            Точки внутри окна объединяются в одну при помощи функции агрегации.


            Значение должно быть больше 0.
          type: string
          format: int64
        aggregation:
          $ref: >-
            #/components/schemas/GridAggregation_in_DataQueryDownsampling_aggregation
        fill:
          $ref: '#/components/schemas/FillGap_in_DataQueryDownsampling_fill'
    GridAggregation_in_DataQueryDownsampling_aggregation:
      description: |-
        Функция агрегации, которая используется для прореживания.

        Список доступных агрегирующий функций, используемых при прореживании.

         - MAX: Максимум.
         - MIN: Минимум.
         - SUM: Сумма.
         - AVG: Среднее значение. Значение по умолчанию.
         - LAST: Последнее значение.
         - COUNT: Количество точек.
      type: string
      enum:
        - MAX
        - MIN
        - SUM
        - AVG
        - LAST
        - COUNT
    FillGap_in_DataQueryDownsampling_fill:
      description: |-
        Параметры заполнения пропусков в данных.

         - NULL: Возвращает `null` в качестве значения метрики и `timestamp` в качестве временной метки. Значение по умолчанию.
         - NONE: Не возвращает значений.
         - PREVIOUS: Возвращает значение из предыдущей временной точки.
      type: string
      enum:
        - 'NULL'
        - NONE
        - PREVIOUS
    MetricKind_in_JsonFormatMetric_kind:
      description: |-
        Тип метрики. Значение по умолчанию — `DGAUGE`.

         - DGAUGE: Числовой показатель. Задается дробным числом.
         - IGAUGE: Числовой показатель. Задается целым числом.
         - COUNTER: Счетчик.
         - RATE: Производная.
      type: string
      enum:
        - DGAUGE
        - IGAUGE
        - COUNTER
        - RATE
    PageOptions_in_ListMetricsResponse_page:
      description: Параметры пагинации.
      type: object
      properties:
        pagesCount:
          description: Количество страниц в ответе.
          type: string
          format: int64
        totalCount:
          description: Общее количество метрик в ответе.
          type: string
          format: int64
        pageSize:
          description: Количество метрик на одной странице ответа.
          type: string
          format: int64
        current:
          description: Номер запрошенной страницы.
          type: string
          format: int64
    MetricKind_in_MetricMeta_kind:
      description: |-
        Тип метрики.

         - DGAUGE: Числовой показатель. Задается дробным числом.
         - IGAUGE: Числовой показатель. Задается целым числом.
         - COUNTER: Счетчик.
         - RATE: Производная.
      type: string
      enum:
        - DGAUGE
        - IGAUGE
        - COUNTER
        - RATE
    MetricKind_in_Timeseries_kind:
      description: |-
        Тип метрики.

         - DGAUGE: Числовой показатель. Задается дробным числом.
         - IGAUGE: Числовой показатель. Задается целым числом.
         - COUNTER: Счетчик.
         - RATE: Производная.
      type: string
      enum:
        - DGAUGE
        - IGAUGE
        - COUNTER
        - RATE
tags:
  - name: MetricsData
    description: Набор методов для управления данными метрик.
  - name: MetricsMeta
    description: Набор методов для получения информации о метаданных метрик.
