openapi: "3.0"
info:
  title: Yandex Speech To Text Service API
  description: This API reference is organized by resource. All actions are performed
    by sending HTTP requests to resource URLs. For more information about Yandex.Cloud
    API architecture, see [API Concepts](/docs/api-design-guide/).
  version: v2
  x-y-docUri: api-ref
  x-y-baseUrl: https://stt.api.cloud.yandex.net
paths:
  /speech/stt/v2/longRunningRecognize:
    post:
      tags:
      - Stt
      operationId: SttLongRunningRecognize
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LongRunningRecognitionRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Operation'
      x-y-navtitle: longRunningRecognize
      x-y-operation-response: '`LongRunningRecognitionResponse`'
components:
  schemas:
    LongRunningRecognitionRequest:
      type: object
      properties:
        config:
          $ref: '#/components/schemas/RecognitionConfig_in_LongRunningRecognitionRequest_config'
        audio:
          $ref: '#/components/schemas/RecognitionAudio_in_LongRunningRecognitionRequest_audio'
    LongRunningRecognitionResponse:
      type: object
      properties:
        chunks:
          type: array
          items:
            $ref: '#/components/schemas/SpeechRecognitionResult'
    Operation:
      description: |-
        Ресурс Operation. Дополнительные сведения см. в разделе
        [Объект Operation](/docs/api-design-guide/concepts/operation).
      type: object
      allOf:
      - type: object
        properties:
          id:
            description: Идентификатор операции.
            type: string
          description:
            description: |-
              Описание операции. Длина описания должна быть от 0 до 256
              символов.
            type: string
          createdAt:
            description: |-
              Время создания ресурса в формате в
              [RFC3339](https://www.ietf.org/rfc/rfc3339.txt).

              Строка в формате [RFC3339](https://www.ietf.org/rfc/rfc3339.txt).
            type: string
            format: date-time
          createdBy:
            description: |-
              Идентификатор пользователя или сервисного
              аккаунта, инициировавшего операцию.
            type: string
          modifiedAt:
            description: |-
              Время, когда ресурс Operation последний раз
              обновлялся. Значение в формате [RFC3339](https://www.ietf.org/rfc/rfc3339.txt).

              Строка в формате [RFC3339](https://www.ietf.org/rfc/rfc3339.txt).
            type: string
            format: date-time
          done:
            description: |-
              Если значение равно `false` — операция еще
              выполняется. Если `true` — операция завершена, и задано значение
              одного из полей `error` или `response`.
            type: boolean
            format: boolean
          metadata:
            description: |-
              Метаданные операции. Обычно в поле содержится
              идентификатор ресурса, над которым выполняется операция. Если
              метод возвращает ресурс Operation, в описании метода приведена
              структура соответствующего ему поля `metadata`.
            type: object
      - title: result
        type: object
        maxProperties: 1
        properties:
          error:
            $ref: '#/components/schemas/Status'
            description: Описание ошибки в случае сбоя или отмены операции.
          response:
            description: |-
              Результат операции в случае успешного завершения. Если
              исходный метод не возвращает никаких данных при успешном
              завершении, например метод Delete, поле содержит объект
              [google.protobuf.Empty](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#empty). Если исходный метод — это стандартный метод Create
              / Update, поле содержит целевой ресурс операции. Если метод
              возвращает ресурс Operation, в описании метода приведена
              структура соответствующего ему поля `response`.
            type: object
    RecognitionAudio:
      type: object
      allOf:
      - title: audio_source
        type: object
        maxProperties: 1
        properties:
          content:
            type: string
            format: byte
          uri:
            type: string
    RecognitionConfig:
      type: object
      properties:
        specification:
          $ref: '#/components/schemas/RecognitionSpec_in_RecognitionConfig_specification'
        folderId:
          type: string
    RecognitionSpec:
      type: object
      properties:
        audioEncoding:
          $ref: '#/components/schemas/RecognitionSpecAudioEncoding_in_RecognitionSpec_audioEncoding'
        sampleRateHertz:
          description: 8000, 16000, 48000 только для pcm
          type: string
          format: int64
        languageCode:
          description: код в формате BCP-47
          type: string
        profanityFilter:
          type: boolean
          format: boolean
        model:
          type: string
        partialResults:
          description: |-
            Если установлено значение true, предварительные гипотезы могут быть возвращены по
            мере их появления (final=false flag). Если false или опущено, возвращаются только final=true result (s).
            Имеет смысл только для запросов StreamingRecognize.
          type: boolean
          format: boolean
        singleUtterance:
          type: boolean
          format: boolean
        audioChannelCount:
          description: Используется только для распознавания длинных аудио.
          type: string
          format: int64
        rawResults:
          description: Эта отметка позволяет отключить нормализацию текста
          type: boolean
          format: boolean
    RecognitionSpecAudioEncoding:
      description: ' - LINEAR16_PCM: 16-bit signed little-endian (Linear PCM)'
      type: string
      enum:
      - LINEAR16_PCM
      - OGG_OPUS
    SpeechRecognitionAlternative:
      type: object
      properties:
        text:
          type: string
        confidence:
          type: number
          format: float
        words:
          type: array
          items:
            $ref: '#/components/schemas/WordInfo'
    SpeechRecognitionChunk:
      type: object
      properties:
        alternatives:
          type: array
          items:
            $ref: '#/components/schemas/SpeechRecognitionAlternative'
        final:
          type: boolean
          format: boolean
    SpeechRecognitionResult:
      type: object
      properties:
        alternatives:
          type: array
          items:
            $ref: '#/components/schemas/SpeechRecognitionAlternative'
        channelTag:
          type: string
          format: int64
    Status:
      description: Описание ошибки в случае сбоя или отмены операции.
      type: object
      properties:
        code:
          description: Код ошибки. Значение из списка [google.rpc.Code](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto).
          type: integer
          format: int32
        message:
          description: Текст ошибки.
          type: string
        details:
          description: Список сообщений с подробными сведениями об ошибке.
          type: array
          items:
            type: object
    StreamingRecognitionResponse:
      type: object
      properties:
        chunks:
          type: array
          items:
            $ref: '#/components/schemas/SpeechRecognitionChunk'
        endOfSingleUtterance:
          type: boolean
          format: boolean
    WordInfo:
      type: object
      properties:
        startTime:
          type: string
        endTime:
          type: string
        word:
          type: string
        confidence:
          type: number
          format: float
    RecognitionConfig_in_LongRunningRecognitionRequest_config:
      type: object
      properties:
        specification:
          $ref: '#/components/schemas/RecognitionSpec_in_RecognitionConfig_specification'
        folderId:
          type: string
    RecognitionAudio_in_LongRunningRecognitionRequest_audio:
      type: object
      allOf:
      - title: audio_source
        type: object
        maxProperties: 1
        properties:
          content:
            type: string
            format: byte
          uri:
            type: string
    RecognitionSpec_in_RecognitionConfig_specification:
      type: object
      properties:
        audioEncoding:
          $ref: '#/components/schemas/RecognitionSpecAudioEncoding_in_RecognitionSpec_audioEncoding'
        sampleRateHertz:
          description: 8000, 16000, 48000 только для pcm
          type: string
          format: int64
        languageCode:
          description: код в формате BCP-47
          type: string
        profanityFilter:
          type: boolean
          format: boolean
        model:
          type: string
        partialResults:
          description: |-
            Если установлено значение true, предварительные гипотезы могут быть возвращены по
            мере их появления (final=false flag). Если false или опущено, возвращаются только final=true result (s).
            Имеет смысл только для запросов StreamingRecognize.
          type: boolean
          format: boolean
        singleUtterance:
          type: boolean
          format: boolean
        audioChannelCount:
          description: Используется только для распознавания длинных аудио.
          type: string
          format: int64
        rawResults:
          description: Эта отметка позволяет отключить нормализацию текста
          type: boolean
          format: boolean
    RecognitionSpecAudioEncoding_in_RecognitionSpec_audioEncoding:
      description: ' - LINEAR16_PCM: 16-bit signed little-endian (Linear PCM)'
      type: string
      enum:
      - LINEAR16_PCM
      - OGG_OPUS
tags:
- name: Stt
